# Generated by Django 5.2.7 on 2025-11-24 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_withdrawal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_agent_sale',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='bundle',
            name='send_via_api',
            field=models.BooleanField(default=False, help_text='If checked, this bundle will be fetched/sold via the data source API.'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='bundle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='network',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bundle'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='recipient',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('PAID', 'Paid'), ('FAILED', 'Failed')], max_length=20),
        ),
    ]
