# Generated by Django 5.2.7 on 2025-11-25 10:45

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_purchase_is_agent_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='agent',
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RenameField(
            model_name='appsettings',
            old_name='BUNDLE_API_KEY',
            new_name='DATA_API_KEY',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='commission_earned',
        ),
        migrations.AddField(
            model_name='appsettings',
            name='DATA_API_BASE_URL',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='bundle',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bundle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='response_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'Admin bundle'), ('API', 'External API')], default='ADMIN', max_length=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='total_sales_volume',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='appsettings',
            name='agent_registration_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='network',
            field=models.CharField(choices=[('MTN', 'MTN'), ('AirtelTigo', 'AirtelTigo'), ('Vodafone', 'Vodafone')], max_length=50),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='send_via_api',
            field=models.BooleanField(default=False, help_text='If checked, this bundle is delivered via configured external API.'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='stock',
            field=models.IntegerField(default=0, help_text='Admin-managed stock (optional).'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bundle_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user'], name='core_purcha_user_id_f0659d_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['transaction_reference'], name='core_purcha_transac_1023f4_idx'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Withdrawal',
        ),
    ]
