# Generated by Django 5.2.7 on 2025-12-02 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
