# Generated by Django 5.2.7 on 2025-12-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_appsettings_created_at_appsettings_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='api_key',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='public_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
