# Generated by Django 5.2.7 on 2025-12-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_agentprofile_api_key_agentprofile_has_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='public_key',
            field=models.CharField(default='PUB-8a9f88058faf4ee3b2cdb2700190d077', max_length=120, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='secret_key',
            field=models.CharField(default='SEC-b7ba9f0665d94e4c88264788cca21497', max_length=120, unique=True),
            preserve_default=False,
        ),
    ]
