# Generated by Django 5.2.7 on 2025-12-04 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_agentprofile_public_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appsettings',
            old_name='DATA_API_KEY',
            new_name='SMART_API_KEY',
        ),
        migrations.RenameField(
            model_name='appsettings',
            old_name='DATA_API_BASE_URL',
            new_name='SMART_BASE_URL',
        ),
    ]
