# Generated by Django 5.2.7 on 2025-12-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_data_api_key_appsettings_smart_api_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='code',
        ),
        migrations.AddField(
            model_name='bundle',
            name='api_package_id',
            field=models.CharField(blank=True, help_text='Future support if API requires a package ID', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='vendor_code',
            field=models.CharField(blank=True, help_text='Package size or vendor code used by SmartDataLink API', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='bundle',
            name='vendor_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='API cost if SmartDataLink charges different price', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price on your platform', max_digits=12),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='send_via_api',
            field=models.BooleanField(default=False, help_text='If True, delivery goes through SmartDataLink API'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='response_data',
            field=models.JSONField(blank=True, help_text='Raw SmartDataLink API response for audit', null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='source',
            field=models.CharField(choices=[('ADMIN', 'Admin Bundle'), ('API', 'SmartDataLink API')], default='ADMIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transaction_reference',
            field=models.CharField(blank=True, help_text='API order reference or paystack reference', max_length=200, null=True),
        ),
    ]
