# Generated by Django 5.2.7 on 2025-12-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_bundle_code_bundle_api_package_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='SMART_API_SECRET',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
